ALTER TYPE "GroupStatus" RENAME VALUE 'DRAWN' TO 'SORTEADO';

ALTER TYPE "NotificationType" RENAME VALUE 'DRAW_INVITATION' TO 'SORTEIO_INVITATION';

ALTER TABLE "Group" RENAME COLUMN "drawnAt" TO "sorteadoAt";
